name: base_project
description: "A new concept of delivering parcel."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 2.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  retrofit: ^4.0.1
  dio: ^5.2.1+1
  shared_preferences: ^2.2.0
  provider: ^6.0.5
  fluttertoast: ^8.2.2
  flutter_spinkit: ^5.2.0
  cached_network_image: ^3.3.1
  connectivity: ^3.0.3
  permission_handler: ^11.3.1
  intl: ^0.18.0
  image_picker: ^1.0.8
  infinite_scroll_pagination: ^4.1.0

dev_dependencies:
  retrofit_generator: ^8.0.6
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/app/